if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/edge_case_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/edge_case_test_e3b0c442_tests.cmake")
else()
  add_test(edge_case_test_NOT_BUILT edge_case_test_NOT_BUILT)
endif()
