if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/inbound_queue_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/inbound_queue_test_e3b0c442_tests.cmake")
else()
  add_test(inbound_queue_test_NOT_BUILT inbound_queue_test_NOT_BUILT)
endif()
