if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/pool_exhaustion_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/pool_exhaustion_test_e3b0c442_tests.cmake")
else()
  add_test(pool_exhaustion_test_NOT_BUILT pool_exhaustion_test_NOT_BUILT)
endif()
