if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/price_level_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/price_level_test_e3b0c442_tests.cmake")
else()
  add_test(price_level_test_NOT_BUILT price_level_test_NOT_BUILT)
endif()
