if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/response_routing_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/response_routing_test_e3b0c442_tests.cmake")
else()
  add_test(response_routing_test_NOT_BUILT response_routing_test_NOT_BUILT)
endif()
