if(EXISTS "C:/Users/harsh/Desktop/MiniExchange/build_check/spsc_ring_buffer_test_e3b0c442_tests.cmake")
  include("C:/Users/harsh/Desktop/MiniExchange/build_check/spsc_ring_buffer_test_e3b0c442_tests.cmake")
else()
  add_test(spsc_ring_buffer_test_NOT_BUILT spsc_ring_buffer_test_NOT_BUILT)
endif()
